import { PrismaClient, ProjectStatus, Priority, BillingType } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding current projects...');

  // Create clients first
  const clients = await Promise.all([
    prisma.client.upsert({
      where: { id: 'client-aloha-massage' },
      update: {},
      create: {
        id: 'client-aloha-massage',
        name: 'Aloha Massage Spa',
        company: 'Aloha Massage Spa',
        email: 'contact@alohamassagespahi.com',
        website: 'https://www.alohamassagespahi.com',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-bos-auto' },
      update: {},
      create: {
        id: 'client-bos-auto',
        name: 'BOS Auto Detail',
        company: 'BOS Auto Detail',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-walter-peters' },
      update: {},
      create: {
        id: 'client-walter-peters',
        name: 'Walter Peters',
        company: 'BG Trading',
        defaultBillingType: BillingType.HOURLY,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-kangen' },
      update: {},
      create: {
        id: 'client-kangen',
        name: 'Kangen Water Hawaii',
        company: 'Kangen Business',
        defaultBillingType: BillingType.RETAINER,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-bgwealth' },
      update: {},
      create: {
        id: 'client-bgwealth',
        name: 'BG Wealth',
        company: 'Benefits Resource Group',
        website: 'https://www.benefitsresourcegroupllc.com',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-lee-meadows' },
      update: {},
      create: {
        id: 'client-lee-meadows',
        name: 'Lee Meadows',
        company: 'Lee Meadows Coaching',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-viethawaii' },
      update: {},
      create: {
        id: 'client-viethawaii',
        name: 'Viet Hawaii',
        company: 'Viet Hawaii Restaurant',
        website: 'https://viethawaii.com',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-drsilke' },
      update: {},
      create: {
        id: 'client-drsilke',
        name: 'Dr. Silke',
        company: 'Dr. Silke Clinic',
        website: 'https://www.sarnoclinic.com',
        defaultBillingType: BillingType.RETAINER,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-pacific-pulse' },
      update: {},
      create: {
        id: 'client-pacific-pulse',
        name: 'Pacific Pulse (Internal)',
        company: 'Pacific Pulse AI',
        defaultBillingType: BillingType.HOURLY,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-echicken' },
      update: {},
      create: {
        id: 'client-echicken',
        name: 'E-Chicken Hawaii',
        company: 'E-Chicken Restaurant',
        website: 'https://www.echickenhi.com',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-truong-viet-ngu' },
      update: {},
      create: {
        id: 'client-truong-viet-ngu',
        name: 'Truong Viet Ngu',
        company: 'Vietnamese Language School',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-xado' },
      update: {},
      create: {
        id: 'client-xado',
        name: 'XADO Hawaii',
        company: 'XADO Hawaii',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-live-safe' },
      update: {},
      create: {
        id: 'client-live-safe',
        name: 'Live Safe Hawaii',
        company: 'Live Safe Hawaii',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-sony-ho' },
      update: {},
      create: {
        id: 'client-sony-ho',
        name: 'Sony Ho',
        company: 'Personal Projects',
        defaultBillingType: BillingType.HOURLY,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-aloha-coaches' },
      update: {},
      create: {
        id: 'client-aloha-coaches',
        name: 'Aloha Coaches',
        company: 'Aloha Coaches',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
    prisma.client.upsert({
      where: { id: 'client-kailua-nail-care' },
      update: {},
      create: {
        id: 'client-kailua-nail-care',
        name: 'Kailua Nail Care',
        company: 'Kailua Nail Care',
        defaultBillingType: BillingType.FIXED,
        isActive: true,
      },
    }),
  ]);

  console.log(`Created ${clients.length} clients`);

  // Create projects
  const projects = [
    {
      id: 'proj-aloha-massage-spa',
      name: 'Aloha Massage Spa',
      description: 'Spa booking and management system with online scheduling, service catalog, and client management.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-aloha-massage',
      clientName: 'Aloha Massage Spa',
      repositoryUrl: 'https://github.com/sonyho2715/aloha-massage-spa',
      deploymentUrl: 'https://www.alohamassagespahi.com',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Build a modern spa booking website with online scheduling capabilities.',
    },
    {
      id: 'proj-bos-auto-detail',
      name: 'BOS Auto Detail Frontend',
      description: 'Auto detailing service frontend with service packages, booking system, and customer portal.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-bos-auto',
      clientName: 'BOS Auto Detail',
      repositoryUrl: 'https://github.com/sonyho2715/bos-auto-detail-frontend',
      billingType: BillingType.FIXED,
      priority: Priority.HIGH,
      initialPrompt: 'Create auto detailing service website with package selection and booking.',
    },
    {
      id: 'proj-bg-walter-peters',
      name: 'BG Trading Dashboard',
      description: 'Trading dashboard application with real-time market data, portfolio tracking, and analytics.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-walter-peters',
      clientName: 'Walter Peters',
      repositoryUrl: 'https://github.com/sonyho2715/bg-walter-peters',
      deploymentUrl: 'https://bg-walter-peters.vercel.app',
      billingType: BillingType.HOURLY,
      priority: Priority.HIGH,
      initialPrompt: 'Build trading dashboard with portfolio management and market analytics.',
    },
    {
      id: 'proj-kangen-autopost',
      name: 'Kangen Autopost',
      description: 'Kangen business automation tools for social media posting and lead management.',
      status: ProjectStatus.MONITORING,
      clientId: 'client-kangen',
      clientName: 'Kangen Water Hawaii',
      repositoryUrl: 'https://github.com/sonyho2715/kangen-autopost',
      billingType: BillingType.RETAINER,
      priority: Priority.MEDIUM,
      initialPrompt: 'Create automation system for Kangen business social media and marketing.',
    },
    {
      id: 'proj-bgwealth',
      name: 'BG Wealth / Benefits Resource Group',
      description: 'Wealth management platform with financial calculators, tools, and client portal.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-bgwealth',
      clientName: 'Benefits Resource Group',
      repositoryUrl: 'https://github.com/sonyho2715/BGWealth',
      deploymentUrl: 'https://www.benefitsresourcegroupllc.com',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Build financial services website with calculators and client resources.',
    },
    {
      id: 'proj-pacific-pulse-growth-lab',
      name: 'Pacific Pulse Growth Lab',
      description: 'Growth lab platform for tracking business metrics, experiments, and growth strategies.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-pacific-pulse',
      clientName: 'Pacific Pulse (Internal)',
      repositoryUrl: 'https://github.com/sonyho2715/pacific-pulse-growth-lab',
      billingType: BillingType.HOURLY,
      priority: Priority.HIGH,
      initialPrompt: 'Internal growth tracking and analytics platform.',
    },
    {
      id: 'proj-lee-meadows-saas',
      name: 'Lee Meadows SaaS',
      description: 'SaaS application for coaching business with client management and session scheduling.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-lee-meadows',
      clientName: 'Lee Meadows',
      repositoryUrl: 'https://github.com/sonyho2715/lee-meadows-saas',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Build coaching SaaS platform with client management features.',
    },
    {
      id: 'proj-viethawaii',
      name: 'Viet Hawaii Restaurant',
      description: 'Vietnamese restaurant platform with online menu, ordering, and reservation system.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-viethawaii',
      clientName: 'Viet Hawaii',
      repositoryUrl: 'https://github.com/sonyho2715/viethawaii',
      deploymentUrl: 'https://viethawaii.com',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Create restaurant website with online ordering and reservations.',
    },
    {
      id: 'proj-drsilke-autopost',
      name: 'Dr. Silke Autopost',
      description: 'Dr. Silke autoposting system for social media content scheduling and management.',
      status: ProjectStatus.MONITORING,
      clientId: 'client-drsilke',
      clientName: 'Dr. Silke',
      repositoryUrl: 'https://github.com/sonyho2715/drsilke-autopost',
      billingType: BillingType.RETAINER,
      priority: Priority.LOW,
      initialPrompt: 'Autoposting system for medical practice social media.',
    },
    {
      id: 'proj-ai-prompts-marketplace',
      name: 'AI Prompts Marketplace',
      description: 'AI prompts marketplace for buying and selling AI prompt templates.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-pacific-pulse',
      clientName: 'Pacific Pulse (Internal)',
      repositoryUrl: 'https://github.com/sonyho2715/ai-prompts-marketplace',
      billingType: BillingType.HOURLY,
      priority: Priority.LOW,
      initialPrompt: 'Build marketplace for AI prompts and templates.',
    },
    {
      id: 'proj-pacific-pulse-kanban',
      name: 'Pacific Pulse AI Projects Kanban',
      description: 'This CRM/project management system for tracking all AI development projects.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-pacific-pulse',
      clientName: 'Pacific Pulse (Internal)',
      billingType: BillingType.HOURLY,
      priority: Priority.URGENT,
      initialPrompt: 'Build comprehensive CRM for managing AI projects with Kanban board.',
    },
    {
      id: 'proj-echicken-website',
      name: 'E-Chicken Website',
      description: 'Restaurant website with online ordering system for E-Chicken Hawaii.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-echicken',
      clientName: 'E-Chicken Hawaii',
      repositoryUrl: 'https://github.com/sonyho2715/echicken-website',
      deploymentUrl: 'https://www.echickenhi.com',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Create restaurant website with online ordering.',
    },
    {
      id: 'proj-truong-viet-ngu',
      name: 'Truong Viet Ngu',
      description: 'Vietnamese language school website with course registration.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-truong-viet-ngu',
      clientName: 'Truong Viet Ngu',
      repositoryUrl: 'https://github.com/sonyho2715/truong-viet-ngu',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Build language school website with course management.',
    },
    {
      id: 'proj-bg-trader-dashboard',
      name: 'BG Trader Dashboard',
      description: 'Advanced trading analytics dashboard with real-time data visualization.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-walter-peters',
      clientName: 'Walter Peters',
      repositoryUrl: 'https://github.com/sonyho2715/bg-trader-dashboard',
      billingType: BillingType.HOURLY,
      priority: Priority.HIGH,
      initialPrompt: 'Build advanced trader analytics dashboard.',
    },
    {
      id: 'proj-kangen-website',
      name: 'Kangen Website',
      description: 'Kangen Water business website with product catalog and distributor info.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-kangen',
      clientName: 'Kangen Water Hawaii',
      repositoryUrl: 'https://github.com/sonyho2715/kangen-website',
      billingType: BillingType.RETAINER,
      priority: Priority.MEDIUM,
      initialPrompt: 'Create Kangen Water business website.',
    },
    {
      id: 'proj-wealth-blueprint-pro',
      name: 'Wealth Blueprint Pro',
      description: 'Financial planning and wealth management platform with tools and calculators.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-bgwealth',
      clientName: 'Benefits Resource Group',
      repositoryUrl: 'https://github.com/sonyho2715/wealth-blueprint-pro',
      billingType: BillingType.FIXED,
      priority: Priority.HIGH,
      initialPrompt: 'Build wealth management platform.',
    },
    {
      id: 'proj-coaching-tools-enhanced',
      name: 'Coaching Tools Enhanced',
      description: 'Enhanced coaching tools platform with client management and session tracking.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-lee-meadows',
      clientName: 'Lee Meadows',
      repositoryUrl: 'https://github.com/sonyho2715/coaching-tools-enhanced',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Build enhanced coaching tools platform.',
    },
    {
      id: 'proj-coaching-client-portal',
      name: 'Coaching Client Portal',
      description: 'Client portal for coaching business with session scheduling and resources.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-lee-meadows',
      clientName: 'Lee Meadows',
      repositoryUrl: 'https://github.com/sonyho2715/coaching-client-portal',
      billingType: BillingType.FIXED,
      priority: Priority.MEDIUM,
      initialPrompt: 'Create client portal for coaching business.',
    },
    {
      id: 'proj-xado-hawaii',
      name: 'XADO Hawaii',
      description: 'Automotive products and services website for XADO Hawaii.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-xado',
      clientName: 'XADO Hawaii',
      repositoryUrl: 'https://github.com/sonyho2715/xado-hawaii',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Build automotive products website.',
    },
    {
      id: 'proj-live-safe-hawaii',
      name: 'Live Safe Hawaii',
      description: 'Safety and security services website for Live Safe Hawaii.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-live-safe',
      clientName: 'Live Safe Hawaii',
      repositoryUrl: 'https://github.com/sonyho2715/live-safe-hawaii',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Create safety services website.',
    },
    {
      id: 'proj-alohacoaches',
      name: 'Aloha Coaches',
      description: 'Coaching platform for Aloha Coaches with team management.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-aloha-coaches',
      clientName: 'Aloha Coaches',
      repositoryUrl: 'https://github.com/sonyho2715/alohacoaches',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Build coaching platform with team features.',
    },
    {
      id: 'proj-bg-dashboards-sales',
      name: 'BG Dashboards Sales',
      description: 'Sales dashboards and analytics for Benefits Group.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-bgwealth',
      clientName: 'Benefits Resource Group',
      repositoryUrl: 'https://github.com/sonyho2715/bg-dashboards-sales',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Create sales analytics dashboard.',
    },
    {
      id: 'proj-sales-gamification',
      name: 'Sales Gamification Platform',
      description: 'Gamification platform for sales teams with leaderboards and rewards.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-bgwealth',
      clientName: 'Benefits Resource Group',
      repositoryUrl: 'https://github.com/sonyho2715/sales-gamification-platform',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Build sales gamification system.',
    },
    {
      id: 'proj-wealth-pro-recruitment',
      name: 'Wealth Pro Recruitment',
      description: 'Recruitment platform for wealth advisors and financial professionals.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-bgwealth',
      clientName: 'Benefits Resource Group',
      repositoryUrl: 'https://github.com/sonyho2715/wealth-pro-recruitment',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Create recruitment platform for advisors.',
    },
    {
      id: 'proj-insurance-calculator',
      name: 'Insurance Calculator',
      description: 'Insurance needs calculator and comparison tool.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-bgwealth',
      clientName: 'Benefits Resource Group',
      repositoryUrl: 'https://github.com/sonyho2715/insurance-calculator',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Build insurance calculator tools.',
    },
    {
      id: 'proj-benefits-resource-group',
      name: 'Benefits Resource Group',
      description: 'Main Benefits Resource Group website with services and resources.',
      status: ProjectStatus.DEPLOYED,
      clientId: 'client-bgwealth',
      clientName: 'Benefits Resource Group',
      repositoryUrl: 'https://github.com/sonyho2715/benefits-resource-group',
      deploymentUrl: 'https://www.benefitsresourcegroupllc.com',
      billingType: BillingType.FIXED,
      priority: Priority.HIGH,
      initialPrompt: 'Build main company website.',
    },
    {
      id: 'proj-walter-peters-trader',
      name: 'Walter Peters Trader',
      description: 'Trading platform for Walter Peters with advanced analytics.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-walter-peters',
      clientName: 'Walter Peters',
      repositoryUrl: 'https://github.com/sonyho2715/walter-peters-trader',
      billingType: BillingType.HOURLY,
      priority: Priority.HIGH,
      initialPrompt: 'Build advanced trading platform.',
    },
    {
      id: 'proj-lee-meadows-bg',
      name: 'Lee Meadows BG',
      description: 'Benefits Group landing page for Lee Meadows coaching services.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-lee-meadows',
      clientName: 'Lee Meadows',
      repositoryUrl: 'https://github.com/sonyho2715/lee-meadows-bg',
      billingType: BillingType.FIXED,
      priority: Priority.LOW,
      initialPrompt: 'Create coaching services landing page.',
    },
    {
      id: 'proj-bg-sony-ho',
      name: 'BG Sony Ho',
      description: 'Personal portfolio and project showcase for Sony Ho.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-sony-ho',
      clientName: 'Sony Ho',
      repositoryUrl: 'https://github.com/sonyho2715/bg-sony-ho',
      billingType: BillingType.HOURLY,
      priority: Priority.LOW,
      initialPrompt: 'Build personal portfolio website.',
    },
    {
      id: 'proj-first-step',
      name: 'First Step',
      description: 'Onboarding and first steps platform.',
      status: ProjectStatus.BACKLOG,
      clientId: 'client-pacific-pulse',
      clientName: 'Pacific Pulse (Internal)',
      repositoryUrl: 'https://github.com/sonyho2715/First-Step',
      billingType: BillingType.HOURLY,
      priority: Priority.LOW,
      initialPrompt: 'Create onboarding platform.',
    },
    {
      id: 'proj-kailua-nail-care',
      name: 'Kailua Nail Care',
      description: 'Modern nail salon website with booking system, service catalog, online scheduling, and client management.',
      status: ProjectStatus.IN_DEVELOPMENT,
      clientId: 'client-kailua-nail-care',
      clientName: 'Kailua Nail Care',
      repositoryUrl: 'https://github.com/sonyho2715/kailua-nail-care',
      deploymentUrl: 'https://kailua-nail-care.vercel.app',
      billingType: BillingType.FIXED,
      priority: Priority.HIGH,
      estimatedHours: 40,
      estimatedBudget: 3500,
      initialPrompt: 'Build a modern nail salon website with online booking system, service catalog, and professional design.',
    },
  ];

  for (const project of projects) {
    await prisma.project.upsert({
      where: { id: project.id },
      update: {
        name: project.name,
        description: project.description,
        status: project.status,
        clientId: project.clientId,
        clientName: project.clientName,
        repositoryUrl: project.repositoryUrl,
        deploymentUrl: project.deploymentUrl,
        billingType: project.billingType,
        priority: project.priority,
        initialPrompt: project.initialPrompt,
      },
      create: project,
    });
  }

  console.log(`Created/updated ${projects.length} projects`);

  // Create some tags
  const tags = [
    { name: 'Next.js', color: '#000000' },
    { name: 'React', color: '#61dafb' },
    { name: 'TypeScript', color: '#3178c6' },
    { name: 'Prisma', color: '#2d3748' },
    { name: 'Tailwind', color: '#38bdf8' },
    { name: 'Vercel', color: '#000000' },
    { name: 'Railway', color: '#0b0d0e' },
    { name: 'SaaS', color: '#8b5cf6' },
    { name: 'E-commerce', color: '#10b981' },
    { name: 'Booking', color: '#f59e0b' },
    { name: 'Dashboard', color: '#3b82f6' },
    { name: 'Automation', color: '#ef4444' },
  ];

  for (const tag of tags) {
    await prisma.tag.upsert({
      where: { name: tag.name },
      update: { color: tag.color },
      create: tag,
    });
  }

  console.log(`Created ${tags.length} tags`);

  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
